# Site settings
title: Juvern See
email: see@juvern.com
description: Programmer in training, tennis coach and wannabe writer
url: https://juvern.github.io/

# Build settings
plugins: []

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
