# Site settings
title: Juvern See
email: see@juvern.com
description: Learning, building, writing and coaching tennis
url: https://juvern.com

# Build settings
plugins: []

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
